export type Product = {
  id: number;
  category: string;
  itemId: string;
  name: string;
  fullPrice: number;
  price: number;
  screen?: string;
  resolution?: string;
  processor?: string;
  capacity?: string;
  color: string;
  ram: string;
  year: number;
  image: string;
  phoneId?: string;
  camera?: string;
  zoom?: string;
  cell?: string[];
};
